development:
  db:
    adapter: mysql2
    host: localhost
    username: time-tracker
    password: 
    database: time-tracker-dev
    pool: 20
production:
  db:
    adapter: mysql2
    host: localhost
    username: root
    password: 
    database: time-tracker-prod